import { ProviderRegistry } from "./provider-registry.js";
import type { ProviderProfile } from "./provider-profile.js";

// ─── Web provider profiles (TGR-6.28.1) ──────────────────────────────────────
// Registered with both colon-style IDs (openai:web) used by CreatorWebBridge
// and underscore-style IDs (openai_web) used by Telegram routing layer.
// Both sets are visible to ProviderRouterV2 / ProviderScore / ProviderPolicy.

export const WEB_PROVIDER_PROFILES: ProviderProfile[] = [
  // ── Underscore-style IDs (Telegram routing layer) ──
  {
    provider_id: "openai_web",
    kind: "web",
    access_tier: "creator_web",
    display_name: "OpenAI Web",
    allowed_modes: ["creator"],
    strengths: ["reasoning", "coding", "planning", "review", "creative"],
    limits: { max_context_tokens: 128000, supports_files: true, supports_images: true, supports_web_research: false, supports_code_execution: false },
    cost: { tier: "medium", metered: false },
    privacy: { level: "external_web", allow_sensitive: false },
    reliability: { score: 9.5, last_known_status: "healthy" },
    enabled: true,
  },
  {
    provider_id: "gemini_web",
    kind: "web",
    access_tier: "creator_web",
    display_name: "Gemini Web",
    allowed_modes: ["creator"],
    strengths: ["research", "multimodal", "reasoning", "summarization"],
    limits: { max_context_tokens: 1000000, supports_files: true, supports_images: true, supports_web_research: true, supports_code_execution: false },
    cost: { tier: "medium", metered: false },
    privacy: { level: "external_web", allow_sensitive: false },
    reliability: { score: 8.5, last_known_status: "healthy" },
    enabled: true,
  },
  {
    provider_id: "qwen_web",
    kind: "web",
    access_tier: "creator_web",
    display_name: "Qwen Web",
    allowed_modes: ["creator"],
    strengths: ["coding", "reasoning", "translation", "summarization"],
    limits: { max_context_tokens: 32000, supports_files: true, supports_images: true, supports_web_research: false, supports_code_execution: false },
    cost: { tier: "low", metered: false },
    privacy: { level: "external_web", allow_sensitive: false },
    reliability: { score: 7.0, last_known_status: "healthy" },
    enabled: true,
  },
  {
    provider_id: "deepseek_web",
    kind: "web",
    access_tier: "creator_web",
    display_name: "DeepSeek Web",
    allowed_modes: ["creator"],
    strengths: ["coding", "reasoning", "review", "research"],
    limits: { max_context_tokens: 64000, supports_files: false, supports_images: false, supports_web_research: false, supports_code_execution: false },
    cost: { tier: "low", metered: false },
    privacy: { level: "external_web", allow_sensitive: false },
    reliability: { score: 8.0, last_known_status: "healthy" },
    enabled: true,
  },
  {
    provider_id: "kimi_web",
    kind: "web",
    access_tier: "creator_web",
    display_name: "Kimi Web",
    allowed_modes: ["creator"],
    strengths: ["planning", "research", "summarization", "review"],
    limits: { max_context_tokens: 200000, supports_files: true, supports_images: false, supports_web_research: false, supports_code_execution: false },
    cost: { tier: "low", metered: false },
    privacy: { level: "external_web", allow_sensitive: false },
    reliability: { score: 7.2, last_known_status: "healthy" },
    enabled: true,
  },
  // ── Local web API providers (FreeGLMKimiAPI bridge) ──
  {
    provider_id: "glm_local_web_api",
    kind: "api",
    access_tier: "local_model",
    display_name: "GLM Local Web API",
    allowed_modes: ["public", "creator", "internal"],
    strengths: ["reasoning", "coding", "planning", "research", "creative"],
    limits: { max_context_tokens: 128000, supports_files: false, supports_images: false, supports_web_research: false, supports_code_execution: false },
    cost: { tier: "free", metered: false },
    privacy: { level: "local", allow_sensitive: true },
    reliability: { score: 7.5, last_known_status: "healthy" },
    enabled: true,
  },
  {
    provider_id: "kimi_local_web_api",
    kind: "api",
    access_tier: "local_model",
    display_name: "Kimi Local Web API",
    allowed_modes: ["public", "creator", "internal"],
    strengths: ["reasoning", "planning", "research", "summarization", "review"],
    limits: { max_context_tokens: 200000, supports_files: false, supports_images: false, supports_web_research: false, supports_code_execution: false },
    cost: { tier: "free", metered: false },
    privacy: { level: "local", allow_sensitive: true },
    reliability: { score: 7.5, last_known_status: "healthy" },
    enabled: true,
  },
  // ── Official API providers ──
  {
    provider_id: "glm_api",
    kind: "api",
    access_tier: "api_model",
    display_name: "GLM API",
    allowed_modes: ["public", "creator", "internal"],
    strengths: ["reasoning", "coding", "planning", "research", "creative"],
    limits: { max_context_tokens: 128000, supports_files: true, supports_images: true, supports_web_research: false, supports_code_execution: false },
    cost: { tier: "low", metered: true },
    privacy: { level: "trusted_cloud", allow_sensitive: true },
    reliability: { score: 8.5, last_known_status: "unknown" },
    enabled: true,
  },
  {
    provider_id: "kimi_api",
    kind: "api",
    access_tier: "api_model",
    display_name: "Kimi API",
    allowed_modes: ["public", "creator", "internal"],
    strengths: ["reasoning", "planning", "research", "summarization", "review"],
    limits: { max_context_tokens: 200000, supports_files: true, supports_images: false, supports_web_research: false, supports_code_execution: false },
    cost: { tier: "low", metered: true },
    privacy: { level: "trusted_cloud", allow_sensitive: true },
    reliability: { score: 8.0, last_known_status: "unknown" },
    enabled: true,
  },
  // ── Mimo providers (official API + browser discovery) ──
  {
    provider_id: "mimo_api",
    kind: "api",
    access_tier: "api_model",
    display_name: "Mimo API",
    allowed_modes: ["public", "creator", "internal"],
    strengths: ["reasoning", "coding", "planning", "creative"],
    limits: { max_context_tokens: 128000, supports_files: true, supports_images: false, supports_web_research: false, supports_code_execution: false },
    cost: { tier: "low", metered: true },
    privacy: { level: "trusted_cloud", allow_sensitive: true },
    reliability: { score: 8.0, last_known_status: "unknown" },
    enabled: true,
  },
  {
    provider_id: "mimo_browser_discovery",
    kind: "web",
    access_tier: "creator_web",
    display_name: "Mimo Browser Discovery",
    allowed_modes: ["creator"],
    strengths: ["reasoning", "research", "planning"],
    limits: { max_context_tokens: 32000, supports_files: false, supports_images: false, supports_web_research: false, supports_code_execution: false },
    cost: { tier: "free", metered: false },
    privacy: { level: "external_web", allow_sensitive: false },
    reliability: { score: 5.0, last_known_status: "unknown" },
    enabled: false,
  },
  // ── MiniMax (UI Automation Browser Provider) ──
  {
    provider_id: "minimax",
    kind: "web",
    access_tier: "creator_web",
    display_name: "MiniMax Agent",
    allowed_modes: ["creator"],
    strengths: ["reasoning", "creative", "planning", "coding"],
    limits: { max_context_tokens: 128000, supports_files: false, supports_images: false, supports_web_research: false, supports_code_execution: false },
    cost: { tier: "free", metered: false },
    privacy: { level: "external_web", allow_sensitive: false },
    reliability: { score: 7.0, last_known_status: "unknown" },
    enabled: true,
  },
  // ── Experimental local providers ──
  {
    provider_id: "kimi_free_local",
    kind: "api",
    access_tier: "local_model",
    display_name: "🧪 Kimi Free Local",
    allowed_modes: ["creator"],
    strengths: ["reasoning", "coding"],
    limits: { max_context_tokens: 32000, supports_files: false, supports_images: false, supports_web_research: false, supports_code_execution: false },
    cost: { tier: "free", metered: false },
    privacy: { level: "local", allow_sensitive: true },
    reliability: { score: 5.0, last_known_status: "unknown" },
    enabled: true,
  },
];

/**
 * Returns all web provider profiles (both colon and underscore ID formats).
 * Useful for health checks, scoring, and display.
 */
export function getWebProviderProfiles(): ProviderProfile[] {
  return WEB_PROVIDER_PROFILES;
}

export function registerBuiltinProviders(registry: ProviderRegistry): void {
  const builtins: ProviderProfile[] = [
    {
      provider_id: "openai:web",
      kind: "web",
      access_tier: "creator_web",
      display_name: "OpenAI Web",
      allowed_modes: ["creator"],
      strengths: ["reasoning", "coding", "planning", "review", "creative", "multimodal"],
      limits: { max_context_tokens: 128000, supports_files: true, supports_images: true, supports_web_research: false, supports_code_execution: false },
      cost: { tier: "medium", metered: true },
      privacy: { level: "external_web", allow_sensitive: false },
      reliability: { score: 9.5, last_known_status: "healthy" },
      enabled: true,
    },
    {
      provider_id: "qwen:web",
      kind: "web",
      access_tier: "creator_web",
      display_name: "Qwen Web",
      allowed_modes: ["creator"],
      strengths: ["summarization", "translation", "creative", "coding"],
      limits: { max_context_tokens: 32000, supports_files: true, supports_images: true, supports_web_research: false, supports_code_execution: false },
      cost: { tier: "low", metered: false },
      privacy: { level: "external_web", allow_sensitive: false },
      reliability: { score: 7.0, last_known_status: "healthy" },
      enabled: true,
    },
    {
      provider_id: "deepseek:web",
      kind: "web",
      access_tier: "creator_web",
      display_name: "DeepSeek Web",
      allowed_modes: ["creator"],
      strengths: ["reasoning", "coding", "review", "research"],
      limits: { max_context_tokens: 64000, supports_files: false, supports_images: false, supports_web_research: false, supports_code_execution: false },
      cost: { tier: "low", metered: false },
      privacy: { level: "external_web", allow_sensitive: false },
      reliability: { score: 8.0, last_known_status: "healthy" },
      enabled: true,
    },
    {
      provider_id: "perplexity:web",
      kind: "web",
      access_tier: "creator_web",
      display_name: "Perplexity Web",
      allowed_modes: ["creator"],
      strengths: ["research", "reasoning", "summarization"],
      limits: { max_context_tokens: 32000, supports_files: true, supports_images: false, supports_web_research: true, supports_code_execution: false },
      cost: { tier: "medium", metered: true },
      privacy: { level: "external_web", allow_sensitive: false },
      reliability: { score: 7.5, last_known_status: "healthy" },
      enabled: false,
    },
    {
      provider_id: "openai:api",
      kind: "api",
      access_tier: "api_model",
      display_name: "OpenAI API",
      allowed_modes: ["public", "creator", "internal"],
      strengths: ["reasoning", "coding", "planning", "review", "creative", "multimodal"],
      limits: { max_context_tokens: 128000, supports_files: true, supports_images: true, supports_web_research: false, supports_code_execution: false },
      cost: { tier: "medium", metered: true },
      privacy: { level: "trusted_cloud", allow_sensitive: true },
      reliability: { score: 9.5, last_known_status: "healthy" },
      enabled: true,
    },
    {
      provider_id: "deepseek:api",
      kind: "api",
      access_tier: "api_model",
      display_name: "DeepSeek API",
      allowed_modes: ["public", "creator", "internal"],
      strengths: ["reasoning", "coding", "review", "research"],
      limits: { max_context_tokens: 64000, supports_files: false, supports_images: false, supports_web_research: false, supports_code_execution: false },
      cost: { tier: "low", metered: true },
      privacy: { level: "trusted_cloud", allow_sensitive: true },
      reliability: { score: 8.0, last_known_status: "healthy" },
      enabled: true,
    },
    {
      provider_id: "qwen:api",
      kind: "api",
      access_tier: "api_model",
      display_name: "Qwen API",
      allowed_modes: ["public", "creator", "internal"],
      strengths: ["summarization", "translation", "creative", "coding"],
      limits: { max_context_tokens: 32000, supports_files: true, supports_images: true, supports_web_research: false, supports_code_execution: false },
      cost: { tier: "low", metered: true },
      privacy: { level: "trusted_cloud", allow_sensitive: true },
      reliability: { score: 7.0, last_known_status: "healthy" },
      enabled: true,
    },
    {
      provider_id: "local:llm",
      kind: "local",
      access_tier: "local_model",
      display_name: "Local LLM",
      allowed_modes: ["public", "creator", "internal"],
      strengths: ["reasoning", "coding", "summarization", "planning"],
      limits: { max_context_tokens: 8192, supports_files: false, supports_images: false, supports_web_research: false, supports_code_execution: false },
      cost: { tier: "free", metered: false },
      privacy: { level: "local", allow_sensitive: true },
      reliability: { score: 6.0, last_known_status: "healthy" },
      enabled: true,
    },
  ];

  // Register colon-style profiles (existing)
  for (const profile of builtins) {
    registry.register(profile);
  }

  // TGR-6.28.1: Register underscore-style web profiles for Telegram routing layer
  for (const profile of WEB_PROVIDER_PROFILES) {
    registry.register(profile);
  }
}
