export { createStrategicPlan, updateStrategicPlan, getPlan, getActivePlans } from "./strategic-planning-engine.js";
export type { PlanPriority, PlanStatus, StrategicPlan } from "./strategic-planning-engine.js";
export { decomposeGoal } from "./goal-decomposition-system.js";
export type { DecomposedGoal, DecomposedPhase } from "./goal-decomposition-system.js";
export { createOrchestration } from "./multi-pack-orchestration.js";
export type { OrchestratedPack, OrchestrationPlan } from "./multi-pack-orchestration.js";
export { updateResourceUsage, checkResourceAvailability } from "./planning-resource-governor.js";
export type { ResourceType, ResourceCheck, ResourceGovernorState } from "./planning-resource-governor.js";
export { checkPlanAgainstDoctrines } from "./doctrine-aware-planning.js";
export type { DoctrineAwareCheck } from "./doctrine-aware-planning.js";
export { proposeAutonomousPlan, approveAutonomousPlan, denyAutonomousPlan, getPendingProposals } from "./autonomous-planning-proposal-queue.js";
export type { AutonomousPlanProposal } from "./autonomous-planning-proposal-queue.js";
export { generateCivilizationRoadmap } from "./civilization-roadmap-generator.js";
export type { RoadmapNode, CivilizationRoadmap } from "./civilization-roadmap-generator.js";
export { freezePlanningBaseline, comparePlanningBaseline } from "./autonomous-planning-baseline-freeze.js";
export type { PlanningBaseline } from "./autonomous-planning-baseline-freeze.js";
export { startGovernedExecution } from "./governed-plan-execution-bridge.js";
export type { GovernedExecution } from "./governed-plan-execution-bridge.js";
export { materializePlanToPacks } from "./plan-to-pack-materializer.js";
export type { MaterializedPack } from "./plan-to-pack-materializer.js";
export { updateDependencyStatus, getDependenciesForPlan, getBlockedDependencies, autoDetectDependencies } from "./plan-execution-dependency-tracker.js";
export type { DependencyStatus, DependencyEntry } from "./plan-execution-dependency-tracker.js";
export { updatePlanProgress } from "./plan-execution-progress-monitor.js";
export type { PlanProgress } from "./plan-execution-progress-monitor.js";
export { detectPlanDrift } from "./plan-drift-detector.js";
export type { PlanDriftEntry } from "./plan-drift-detector.js";
export { renderPlanReport, sendPlanReport } from "./plan-mission-control-report.js";
export type { PlanReport } from "./plan-mission-control-report.js";
export { createClosureReport } from "./plan-closure-report.js";
export type { ClosureReport } from "./plan-closure-report.js";
export { freezePlanExecutionBaseline, comparePlanExecutionBaseline } from "./plan-execution-baseline-freeze.js";
export type { PlanExecutionBaseline } from "./plan-execution-baseline-freeze.js";
export { createPlanEvidenceBundle } from "./plan-evidence-bundle.js";
export type { EvidenceBundle } from "./plan-evidence-bundle.js";
export { createVerificationMatrix } from "./plan-verification-matrix.js";
export type { VerificationEntry, VerificationMatrix } from "./plan-verification-matrix.js";
export { updateRiskLedger, getRisksForPlan, getCriticalRisks } from "./plan-risk-ledger.js";
export type { RiskEntry } from "./plan-risk-ledger.js";
export { selectRecoveryPlaybook, executeRecoveryPlaybook } from "./plan-recovery-playbooks.js";
export type { PlaybookType, RecoveryPlaybook } from "./plan-recovery-playbooks.js";
export { createLearningProposal } from "./plan-learning-proposal.js";
export type { LearningProposal } from "./plan-learning-proposal.js";
export { createCanonPromotionCandidate } from "./plan-canon-promotion-bridge.js";
export type { CanonPromotionCandidate } from "./plan-canon-promotion-bridge.js";
export { exportPlanArchive } from "./plan-archive-export.js";
export { freezePlanningCivilization } from "./planning-civilization-freeze.js";
export type { PlanningCivilizationFreeze } from "./planning-civilization-freeze.js";
